---
- name: Cleanup overcloud nodes host vars
  hosts: localhost
  tags: host_vars
  roles:
      - { role: hostvars, action: cleanup, pattern: "{{ provisioner.prefix }}*" }

- name: Provision OpenStack resources
  tags: openstack-setup
  hosts: localhost
  roles:
      - { role: provisioner/openstack, action: "setup" }

- name: Provision Baremetal controller (BMC)
  hosts: bmc
  become: yes
  tags: bmc-setup
  roles:
      - { role: provisioner/openstack/bmc, when: "'bmc' in groups" }

- name: Save overcloud nodes host vars
  hosts: localhost
  tags: host_vars
  roles:
      - { role: hostvars, action: save, host_names: "{{ groups['overcloud_nodes'] }}" }

- name: OpenStack Provisioner SSH wait
  hosts: openstack_nodes:!ovb
  gather_facts: no
  tasks:
  - name: Waiting for OpenStack nodes to be SSH-able
    wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 22
        search_regex: OpenSSH
        delay: 10
        timeout: 500
    delegate_to: localhost
